name: Build and Test                   
on:
  push:                              
    branches:
      - master                         
jobs:
  build:                                
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code             
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with: 
          java-version: "17"
          distribution: temurin
      - name: Test
        run: mvn test
      - name: Build
        run: mvn clean package

      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          username: ${{ secret.MY_SECRET_USERNAME }}
          password: ${{ secret.MY_SECRET_PASSWORD }}
      
      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rohitballer/githubafternoon:1.1





